### ISSUE TITLE
stdlib conflicts

### ISSUE THREAD

**Issue by plukevdh** [datanoise/openssl.cr#13]
Posted an issue here and raising here as well, as it likely has to do with how this lib is being implemented.

https://github.com/manastech/crystal/issues/2168

For reference, you can see the issue here: https://github.com/plukevdh/crystal-lib-conflicts

Several constants defined in `lib_crypto.cr` conflict with constants required by the stdlib implementation. This generally wouldn't be a problem, but several _other_ libs within stdlib (like `HTTP::Request`) cause the runtime to explode. Curious on thoughts as how this might be resolved either by mechanisms existing within Crystal (I'm new to the language) or by changing implementations here. Or better yet, get these fantastic updates merge over to Crystal stdlib proper.

**Comment by benoist** [comment]
Asterite has already indicated that he would like this code all to be merged in the stdlib. I've moved a few bits to the stdlib and they all got merged in.

**Comment by plukevdh** [comment]
I mostly need the extended SHA\* support (SHA224 SHA256 SHA384 SHA512) that the stdlib doesn't support.

**Comment by asterite** [comment]
Yes, please send PR with these additions :-)
